config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    resources :comments, only: :create
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :message, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :picture, presence: true
  validates :caption, presence: true
  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || stored_location_for(resource) || root_path
  end
  
  def render_not_found
    render text: 'Not found', status: :not_found
  end

  def render_forbidden
    render text: 'Forbidden', status: :forbidden
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!, only: [:create]

  def create
    @post = Post.find_by_id(params[:post_id])
    return render_not_found if @post.blank?
    @post.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private
  
  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @posts = Post.order(created_at: :desc).paginate(:page => params[:page], :per_page => 4)
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
  end

  def edit
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_forbidden if @post.user != current_user
  end

  def update
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_forbidden if @post.user != current_user
    @post.update_attributes(post_params)
    if @post.valid?
      redirect_to post_path(@post)
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    return render_not_found if @post.blank?
    return render_forbidden if @post.user != current_user
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :caption, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple Post</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "SP", root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "New", new_post_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :get %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="jumbotron">
      <div class="container">
        <h2> Simple Post.</h2>
      </div>
    </div>
  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert"><%= alert %></p>
  <% end %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h2>Edit Post</h2>
  <%= simple_form_for @post do |f| %>
    <%= f.input :title %>
    <%= f.input :caption %>
    <%= f.submit "Update", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/index.html.erb
<style> 
  .navbar-default {
    margin: 0;
  }

</style>
<div class="col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2" style="margin-top: 10px">
<% @posts.each do |post| %>
  <h2 class="post-title"><%= post.title %></h2>
  <p><%= post.caption %></p>
  <p><%= image_tag post.picture %></p>
    <% post.comments.each do |comment| %>
         <!--  <p><%= comment.user.email %></p> -->
          <p><%= comment.message %></p>
      <% end %>
      <%= simple_form_for Comment.new, url: post_comments_path(post) do |f| %>
        <%= f.input :message, label: false %>
        <%= f.submit 'Comment', class: 'btn btn-success' %>
        <hr>
      <% end %>
<% end %>
  <div style="text-align:center">
    <%= will_paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<style>
  .jumbotron {
    display: none;
  }
</style>
<div class="col-md-6 col-md-offset-3">
  <h2>Post</h2>
  <%= simple_form_for @post do |f| %>
    <%= f.input :picture %>
    <%= f.input :title %>
    <%= f.input :caption %>
    <%= f.submit "Post", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<style>
  .jumbotron {
    display: none;
  }
</style>
<div class="col-md-6 col-md-offset-3">
<h2 class="post-title"><%= @post.title %></h2>
<p><%= @post.caption  %></p>

<% if current_user && current_user == @post.user %>
      <%= link_to edit_post_path(@post) do%>
      <button class="btn btn-success">Edit</button>
      <% end %>
      <%= link_to post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this?"} do %>
      <button class="btn btn-default">Delete</button>
      <% end %>
<% end %>